[[call]]
call_type = "deploy"
class_hash = "0x17b946d2ff930604756b54af37a6552b681a524f8704ee39dfd01d182a2f427"
inputs = []
id = "contract_1_part_1"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x239d6a9303dd2a4cfdf4efaae568df8b8147e82c1639f90851d9a80384c43d0"
inputs = []
id = "contract_1_part_2"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x50a0554c1d5cba00ae4745796fa64a81a1fb99171fd4ee33afde30d9763604a"
inputs = []
id = "contract_1_part_3"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x49ae0d9fb298ec404703a6029c56b0be80623bd72a13cb3b80dba58f9104dc9"
inputs = []
id = "contract_1_part_4"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x2236d23d77342ccdc460ec017c40653ea90f02179cb29d4b37bc88deaa29fde"
inputs = []
id = "contract_1_part_5"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x1fa8c0caf52b8d87129dc811879ce9526d55a21486e053cd3fcd412e5373eea"
inputs = []
id = "contract_1_part_6"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x78223c837100de57d98180c660d20ca69324eaf1ca77f778173b12f506be768"
inputs = []
id = "contract_1_part_7"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x07a34aa6757602c2aab48861849df5b9fb6be39e6a625e9fdefe1d470e1425aa"
inputs = ["0x7", "contract_1_part_1", "contract_1_part_2", "contract_1_part_3", "contract_1_part_4", "contract_1_part_5", "contract_1_part_6", "contract_1_part_7"]
id = "contract_1"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x3cef34bc5fa15938e0c8401398ee96d2277c4b1bd0855f952b8770e14a3f7d6"
inputs = []
id = "contract_2_part1"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x1b9ef9fafe141c000ae467f43d8a9efad39343890ef827e9d2268977a82b889"
inputs = []
id = "contract_2_part2"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x14a87df70bd5abca9fb1c0483017dfe1c78e14144a9ccfa40acd916e9290dbb"
inputs = ["contract_2_part1", "contract_2_part2"]
id = "contract_2"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x0773ee3a60343f252127645db51ac3750be118339f647b69e0a9f43c359aac40"
inputs = ["contract_1", "contract_2"]
id = "main_contract"
unique = false