name: Applicative Recursion - Formatting & Testing

on:
  push:
  pull_request:

jobs:
  applicative-recursion-formatting-and-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            applicative_recursion
          sparse-checkout-cone-mode: false

      - name: Move to directory
        run: |
          mv applicative_recursion/* .
          rm -rf applicative_recursion

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1

      - name: Format code
        run: scarb fmt -w src -c

      - name: Run tests
        run: scarb test
