name: Continuous Integration - proof verification tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-proof-cairo0:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cairo_version: ["cairo0"]
        layout: ["dex", "recursive", "recursive_with_poseidon", "small", "starknet", "starknet_with_keccak"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
      
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Configure layout
        run: python configure.py -l ${{ matrix.layout }} -s keccak
      
      - name: Build project
        run: scarb build
      
      - name: Run verification
        run: cargo run --release --bin runner -- -p target/dev/cairo_verifier.sierra.json -c ${{ matrix.cairo_version }} < examples/proofs/${{ matrix.layout }}/${{ matrix.cairo_version }}_example_proof.json

  verify-proof-cairo1:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          cairo_version: ["cairo1"]
          layout: ["dex", "recursive", "recursive_with_poseidon", "small", "starknet", "starknet_with_keccak"]
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        
        - name: Setup Scarb
          uses: software-mansion/setup-scarb@v1
        
        - name: Setup Rust toolchain
          uses: actions-rust-lang/setup-rust-toolchain@v1
        
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.10'
        
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        - name: Configure layout
          run: python configure.py -l ${{ matrix.layout }} -s keccak
        
        - name: Build project
          run: scarb build
        
        - name: Test project
          run: scarb test
        
        - name: Run verification
          run: cargo run --release --bin runner -- -p target/dev/cairo_verifier.sierra.json -c ${{ matrix.cairo_version }} < examples/proofs/${{ matrix.layout }}/${{ matrix.cairo_version }}_example_proof.json